# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Ovm < Formula
  desc "Local control plane for Claude Code and Codex sessions in one fast TUI"
  homepage "https://github.com/jfrantz-cw/overmind"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jfrantz-cw/overmind/releases/download/v1.0.0/overmind-v1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "898305a527d245fab85e70a907193c39466ad3ecd4c8b9f3f6bba29af3214f20"
    end
    on_intel do
      url "https://github.com/jfrantz-cw/overmind/releases/download/v1.0.0/overmind-v1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "3d73f5ae2e70ca5cbd65aab47977a24478f300911fc2375e732d9e00dfa305c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jfrantz-cw/overmind/releases/download/v1.0.0/overmind-v1.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6fce664a3bdd30b77ce83d30dd599e0a3a5c78f7e0451c000d1b9f8eb9df5918"
    end
  end

  def install
    # The TUI resolves overmind-daemon next to its own exe, so all four must
    # land in the same bin.
    bin.install "ovm", "overmind-daemon", "overmind-orchestrate", "claude-here"
    pkgshare.install "templates"
  end

  def caveats
    <<~CAVEAT
      The command is `ovm`. An unrelated Procfile process manager owns
      `overmind` in homebrew-core.

      Overmind needs at least one provider CLI on PATH (claude, codex, or both).
      Full Codex mutation support requires codex-cli 0.144.6; other versions
      stay in observe-only mode.

      /launch resolves templates from ~/.claude/overmind/templates, which a
      formula cannot write. To enable the bundled templates:
        mkdir -p ~/.claude/overmind/templates
        cp -Rn #{pkgshare}/templates/. ~/.claude/overmind/templates/
    CAVEAT
  end

  test do
    assert_match "overmind #{version}", shell_output("#{bin}/ovm --version")
  end
end
